### PR TITLE
Add missing tests and adjust existing ones

### PR DESCRIPTION
**Pull request by JoschuaGoetz**
I had to change code to test it. FridgeContent.fetchAll had to be changed. @DennisRein You mainly have to check for theses changes

### CODE REVIEW

**Comment by DennisRein** [comment]
Why do we have to pass a mock client only in the fridgeRepository?

Maybe we could store somewhere a static client variable and change it depending on if we are testing or productive? Might even simplify the tests.  

But that's only my take, maybe there is a reason why we shouldn't sore it like that.

**Comment by JoschuaGoetz** [comment]
> Why do we have to pass a mock client only in the fridgeRepository?
You create a contentRepository in a function of the fridgeRepository. In order to mock the requests in the created contentRepository you need to add the client.

You are right. This is not the best solution for this problem. I will experiment with other possibilities and notify you.

**Comment by JoschuaGoetz** [comment]
> Maybe we could store somewhere a static client variable and change it depending on if we are testing or productive? Might even simplify the tests.

Having multiple clients might be favorable, i don`t think it would be a good idea to have a global version of a client. I would rather have a client for each client.

**Comment by DonkeyCo** [comment]
I agree with Joschua. It's not a good idea to mix up testing variables with productive variables.

**Comment by JoschuaGoetz** [comment]
I think the best solution would be to use the client object of the fridge repository. This options removes the parameter from fetchAll. 
The only thing i don`t like is that the fridgeRepository has the same client as the contentRepository. Do we want to add additional code to solve this issue or do we accept this in this occasion ?

**Comment by DennisRein** [comment]
Looks fine to me.

**Pull request merged**
